version: '2'
services:
  nginx:
   image: nginx:alpine
   volumes:
     # SUBISTITUIR PARA O DIRETORIO LOCAL
     - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:rw     
   ports:
     - "80:80"
   environment:
     # TROCAR PARA O IP LOCAL
     - NGINX_HOST=192.168.1.102
     - NGINX_PORT=80
   command: [nginx-debug, '-g', 'daemon off;']
